Repository lokalkauf/lokalkauf-frontend, pull requests merged in 2020-05, with the labels that each got.

#101 refactoring location search - frontend
  src/app/customer/trader-item/trader-item.component.html
  src/app/customer/trader-item/trader-item.component.ts
  src/app/customer/trader-overview/trader-overview.component.ts
  src/app/customer/trader-overview/trader-overview.component2.html
  src/app/models/paging.ts
  src/app/services/image.service.ts
  src/app/services/location.service.spec.ts
  src/app/services/location.service.ts
  src/environments/environment.ts
Labels: refactoring

#104 Trader thumbnail and spinner fix #102
  src/app/customer/trader-item/trader-item.component.html
  src/app/customer/trader-item/trader-item.component.ts
  src/app/customer/trader-overview/trader-overview.component.ts
Labels: bug

#103 #95 save profile - more solid
  src/app/trader/registration/registration.component.html
  src/app/trader/registration/registration.component.scss
  src/app/trader/registration/registration.component.ts
Labels: bug

#98 Trader list rework
  src/app/customer/trader-item/trader-item.component.html
  src/app/customer/trader-item/trader-item.component.scss
  src/app/customer/trader-overview/trader-overview.component.scss
  src/app/customer/trader-overview/trader-overview.component.ts
  src/app/customer/trader-overview/trader-overview.component2.html
  src/theme/styles.scss
Labels: enhancement

#110 add default radius of 10 and fixed whole city sel.
  src/app/services/geo.service.ts
Labels: bug

#107 Merge fix release 4
  src/app/customer/trader-contact/trader-contact.component.ts
  src/app/customer/trader-detail/trader-detail.component.ts
  src/app/customer/trader-overview/trader-overview.component.scss
  src/app/customer/trader-overview/trader-overview.component.ts
  src/app/customer/trader-overview/trader-overview.component2.html
  src/app/reusables/lk-map/lk-map.component.ts
  src/app/services/geo.service.ts
  src/app/start/start.component.ts
  src/app/trader/create-product/create-product.component.ts
  src/app/trader/password-reset/password-reset.component.ts
  src/app/trader/registration/registration.component.html
  src/app/trader/registration/registration.component.ts
  src/app/verify/verify.component.ts
Labels: bug

#112 limit radius data from 5 to 100 regardless of given values in query s…
  src/app/customer/trader-overview/trader-overview.component.ts
Labels: bug

#129 #121 different urls for mobile and desktop
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/customer/trader-overview/trader-overview.component.ts
  src/app/customer/trader-overview/trader-overview.component2.html
Labels: bug

#130 Text Changes
  src/app/trader/password-reset/password-reset.component.html
  src/app/trader/profile/profile.component.html
  src/app/trader/registration/registration.component.html
Labels: enhancement

#128 #122 enable confirmation after fly end
  src/app/reusables/lk-map/lk-map.component.ts
  src/app/trader/registration/registration.component.html
  src/app/trader/registration/registration.component.ts
Labels: bug

#132 new text for startpage
  src/app/services/uiTexts.ts
Labels: enhancement

#80 basic implementation of cookie bar
  angular.json
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/theme/styles.scss
Labels: enhancement

#141 browser detection to prevent upload on old or unsupported browsers
  ATTRIBUTION.md
  browserslist
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/reusables/image-chooser/image-chooser.component.ts
  src/app/services/browser.service.ts
  src/app/services/email.service.ts
  src/app/services/geo.service.ts
  src/app/services/image.service.ts
  src/app/services/location.service.ts
  src/app/services/trader.service.ts
  src/app/services/uiTexts.ts
  src/app/trader/login/login.component.html
  src/app/trader/profile/image-upload/image-upload.component.html
  src/app/trader/profile/image-upload/image-upload.component.ts
  src/index.html
  src/polyfills.ts
  tsconfig.json
Labels: enhancement

#149 do some styling on cookie bar
  ATTRIBUTION.md
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/start/start.component.ts
  src/assets/cookie.svg
  src/theme/styles.scss
Labels: refactoring

#165 force removal of cookie
  src/app/app.component.ts
Labels: bug

#169 replace social media image
  src/assets/lokalkaufSocialMedia.png
  src/index.html
Labels: enhancement

#168 add 3rd party licenses to footer
  src/app/app.component.html
Labels: documentation

#167 add supporters to the about page
  src/app/about-us/about-us.component.html
  src/app/about-us/about-us.component.scss
Labels: enhancement

#166 display bigger thumbnails
  src/app/customer/trader-overview/trader-overview.component.ts
  src/app/services/image.service.ts
Labels: enhancement

#173 cookie banner corrections in UI for mobile devices, tweak footer if m…
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/app.module.ts
  src/theme/styles.scss
Labels: bug, enhancement

#175 delete method contains multiple domain variations
  src/app/app.component.ts
Labels: bug
