Repository lokalkauf/lokalkauf-frontend, pull requests merged in 2020-06, with the labels that each got.

#178 text changes
  src/app/about-us/about-us.component.html
  src/app/app.module.ts
Labels: enhancement

#157 Products
  .gitmodules
  README.md
  firebase.json
  firestore.indexes.json
  firestore.rules
  src/app/customer/customer.module.ts
  src/app/customer/product-detail/product-detail.component.html
  src/app/customer/product-detail/product-detail.component.ts
  src/app/customer/product-item/product-item.component.html
  src/app/customer/product-item/product-item.component.scss
  src/app/customer/product-item/product-item.component.ts
  src/app/customer/product-overview/product-overview.component.html
  src/app/customer/product-overview/product-overview.component.ts
  src/app/customer/trader-detail/trader-detail.component.html
  src/app/customer/trader-detail/trader-detail.component.scss
  src/app/customer/trader-detail/trader-detail.component.ts
  src/app/models/product.ts
  src/app/reusables/image-chooser/image-chooser.component.html
  src/app/reusables/image-chooser/image-chooser.component.ts
  src/app/reusables/lk-product-item/lk-product-item.component.html
  src/app/reusables/lk-product-item/lk-product-item.component.scss
  src/app/reusables/lk-product-item/lk-product-item.component.spec.ts
  src/app/reusables/lk-product-item/lk-product-item.component.ts
  src/app/reusables/reusables.module.ts
  src/app/services/image.service.ts
  src/app/services/product.service.ts
  src/app/services/user.service.ts
  src/app/trader/create-product/create-product.component.html
  src/app/trader/create-product/create-product.component.ts
  src/app/trader/profile/products/create-product/create-product.component.html
  src/app/trader/profile/products/create-product/create-product.component.scss
  src/app/trader/profile/products/create-product/create-product.component.spec.ts
  src/app/trader/profile/products/create-product/create-product.component.ts
  src/app/trader/profile/products/products.component.html
  src/app/trader/profile/products/products.component.scss
  src/app/trader/profile/products/products.component.spec.ts
  src/app/trader/profile/products/products.component.ts
  src/app/trader/profile/profile.component.html
  src/app/trader/trader.module.ts
  src/index.html
  src/theme/styles.scss
  storage.rules
Labels: epic

#170 inital new corousel
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/customer/customer.module.ts
  src/app/customer/trader-detail/trader-detail.component.html
  src/app/customer/trader-detail/trader-detail.component.scss
  src/app/customer/trader-detail/trader-detail.component.ts
  src/app/reusables/lk-testimonal/lk-testimonial.component.html
  src/app/reusables/lk-testimonal/lk-testimonial.component.scss
  src/app/reusables/lk-testimonal/lk-testimonial.component.ts
  src/app/reusables/reusables.module.ts
  src/app/start/start.component.html
  src/app/start/start.component.ts
  src/theme/styles.scss
Labels: enhancement

#188 texts
  src/app/about-us/about-us.component.html
Labels: bug
